[workspace]
members = ["crates/parser", "xabc"]
resolver = "1"

[workspace.package]
name = "xabc"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
rs-xabc = { version = "0.1.0", path = "crates/rs-xabc", default-features = false }
